name: Sync
on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Sync branches
        uses: TreTuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.TOKEN_OF_GITHUB}}
          FROM_BRANCH: production
          TO_BRANCH: develop
          PULL_REQUEST_TITLE: 'update: sync from production to develop'
          PULL_REQUEST_BODY: New code has just landed in production
